WIP sensu_client now works with no debs

diff --git a/packages/ruby/packaging b/packages/ruby/packaging
--- a/packages/ruby/packaging
+++ b/packages/ruby/packaging
@@ -17,29 +17,38 @@
 # under the License.
 #
 # Original Source:
-# https://github.com/logsearch/logsearch-boshrelease
+# https://github.com/cloudfoundry-community/jenkins-boshrelease
 # -------------------------------------------------------------------
 
 set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
 
-# Detect # of CPUs so make jobs can be parallelized
-CPUS=$(grep -c ^processor /proc/cpuinfo)
+RUBY_VERSION=2.1.3
+RUBYGEMS_VERSION=2.4.1
+BUNDLER_VERSION="1.7.3"
 
-# Available variables
-# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
-# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
-export HOME=/var/vcap
+CORES=`grep -c "^processor" /proc/cpuinfo`
 
-PYTHON_VERSION="Python-2.7.8"
-
-tar xfv python/${PYTHON_VERSION}.tgz
-
+tar xzf ruby/ruby-${RUBY_VERSION}.tar.gz
 (
-    cd ${PYTHON_VERSION}
-    ./configure --prefix=${BOSH_INSTALL_TARGET} --enable-shared
-    make -j${CPUS} && make install
+  set -e
+  cd ruby-${RUBY_VERSION}
+  ./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=/var/vcap/packages/libyaml
+  make -j${CORES}
+  make install
 )
 
-# Alternatively, to copy archive contents:
-# cp -a ${PYTHON_VERSION}/* $BOSH_INSTALL_TARGET
+tar zxvf ruby/rubygems-${RUBYGEMS_VERSION}.tgz
+(
+  set -e
+  cd rubygems-${RUBYGEMS_VERSION}
+
+  ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
+
+  if [[ $? != 0 ]] ; then
+    echo "Cannot install rubygems"
+    exit 1
+  fi
+)
+
+${BOSH_INSTALL_TARGET}/bin/gem install ruby/bundler-${BUNDLER_VERSION}.gem --no-ri --no-rdoc
